export const sampleData1 = [
    {
        "id": 34,
        "user_name": "theayushyadav11",
        "first_name": "Ayush",
        "last_name": "Yadav",
        "email": "lit2023049@iiitl.ac.in",
        "password": "$2b$12$FpwYNUwYIR0AIRm8E0Q8Z.WaAJ8czNtLOUepqcsSqzOcI1A2VJFGO",
        "age": 20,
        "gender": "Male",
        "location": "Johnpur",
        "openness": "ambivert",
        "interests": "Spirituality",
        "exp_qual": "Rich",
        "relation_type": "longTerm",
        "social_habits": "Engagement Travelling",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.4422235897316127/WhatsApp Image 2024-08-24 at 17.57.53_50d7ab9b.jpg",
        "score": 33,
        "uuid": "805803d8-915f-48e9-bef3-ed0104d18c41",
        "created_at": "2024-08-24T12:32:09.968122"
    },
    {
        "id": 44,
        "user_name": "piynay",
        "first_name": "Rishu",
        "last_name": "gupta",
        "email": "piyush@gmail.com",
        "password": "$2b$12$Jlg85FdIZOInsvP3NbJu0.aQawFM4fhsct0c6FLMU2pEP90Vv9XSO",
        "age": 20,
        "gender": "Male",
        "location": "delhi",
        "openness": "ambivert",
        "interests": "badminton table tennis",
        "exp_qual": "bas zinda ho",
        "relation_type": "longTerm",
        "social_habits": "drinking",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.994267519114596/starbucks.jpg",
        "score": 28,
        "uuid": "e7bd8b88-203b-4ad7-b9a4-0a592eaa9ba3",
        "created_at": "2024-08-26T09:00:08.968415"
    },
    {
        "id": 32,
        "user_name": "maneesh",
        "first_name": "Maneesh",
        "last_name": "Shukla",
        "email": "lit2023040@iiitl.ac.in",
        "password": "$2b$12$20.Bz9.//ekKTLaSTgJ2guzRKt7tT7Sm8H3OOcUOOxUuDIVxX.PXK",
        "age": 20,
        "gender": "Male",
        "location": "Pratapgarh",
        "openness": "extrovert",
        "interests": "Lund",
        "exp_qual": "beautiful honest respect loyal",
        "relation_type": "shortTerm",
        "social_habits": "Nightout ",
        "past_relations": "no",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.1478504532002327/WhatsApp Image 2024-08-24 at 17.25.20_71a8bb0f.jpg",
        "score": 50,
        "uuid": "20245b74-b245-45c7-90b5-d5322a11b433",
        "created_at": "2024-08-24T11:55:59.676097"
    },
    {
        "id": 37,
        "user_name": "sarthakxtiwari",
        "first_name": "Sarthak",
        "last_name": "Tiwari",
        "email": "sarthaktiwari611@gmail.com",
        "password": "$2b$12$rH72RAVsjCbVHFCx56Wncu.wVr6BA2RYGSEvyliDGvv4a4lgZo26a",
        "age": 19,
        "gender": "Male",
        "location": "IIIT, Lucknow",
        "openness": "extrovert",
        "interests": "Music and good cinema",
        "exp_qual": "Hot af",
        "relation_type": "casual",
        "social_habits": "Takative",
        "past_relations": "Yes",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.09257066397492619/308a8dcb-b739-4f3e-b3d5-f2e10b3ba1e1.jpg",
        "score": 28,
        "uuid": "b2b302f9-cffc-4791-aa7d-e980e3755a38",
        "created_at": "2024-08-26T08:37:39.472040"
    },
    {
        "id": 49,
        "user_name": "ShreyashDhoot",
        "first_name": "Shreyash",
        "last_name": "Dhoot",
        "email": "shreyashdhoot@gmail.com",
        "password": "$2b$12$2ePJW5tbhqogJvWu0OoMuueNtkIh9u3Nq8pSUMsbcZU8Bk092FxVW",
        "age": 19,
        "gender": "Male",
        "location": "Pune,Maharashtra",
        "openness": "ambivert",
        "interests": "cooking,hiking,running,cinefile",
        "exp_qual": "funny,outgoing,intresting,foodie",
        "relation_type": "longTerm",
        "social_habits": ".",
        "past_relations": "Yes",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.4428193964712901/IMG20240107175148.jpg",
        "score": 33,
        "uuid": "778e536c-c1b7-421b-89cf-4cb59deac491",
        "created_at": "2024-08-26T09:37:31.091455"
    },
    {
        "id": 50,
        "user_name": "Pranay26",
        "first_name": "Pranay",
        "last_name": "Deshpande",
        "email": "pranayd2005@gmail.com",
        "password": "$2b$12$6WnIl/mVUEmp203VkFMvUOb9QYvpkIgTE.Gozz5qcrcMLOEJpBIQS",
        "age": 20,
        "gender": "Male",
        "location": "Lucknow",
        "openness": "ambivert",
        "interests": "Cricket,football,guitar",
        "exp_qual": "Tall and skilled in backed react",
        "relation_type": "casual",
        "social_habits": "",
        "past_relations": "Yes",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "",
        "score": 25,
        "uuid": "a142ab6e-41ae-42e5-a055-dfec9c04c8c7",
        "created_at": "2024-08-26T09:39:06.057856"
    },
    {
        "id": 38,
        "user_name": "anujgarg",
        "first_name": "Karan",
        "last_name": "Agarwal",
        "email": "lit2023011@iiitl.ac.in",
        "password": "$2b$12$CIUnG2.Ya7RkJJWLjLJEP.0REyokdzjxxc84cOCZbVhCc6SmKNU5e",
        "age": 20,
        "gender": "Male",
        "location": "Agra",
        "openness": "extrovert",
        "interests": "Sports",
        "exp_qual": "Love",
        "relation_type": "casual",
        "social_habits": "Talking",
        "past_relations": "Yes",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.5071031884144366/WhatsApp Image 2024-08-26 at 14.06.37_fa4db545.jpg",
        "score": 40,
        "uuid": "45ff40b0-2234-454d-8dbe-41f8b3ac5b16",
        "created_at": "2024-08-26T08:37:54.139906"
    },
    {
        "id": 33,
        "user_name": "aman",
        "first_name": "Aman",
        "last_name": "Vishwakarma",
        "email": "lit2023032@iiitl.ac.in",
        "password": "$2b$12$oxe61ycUwEm1h9EEh1ZBiefBhCMO8P0Y.qXzYfWSabimSTeiyq3R.",
        "age": 20,
        "gender": "Male",
        "location": "Lucknow",
        "openness": "ambivert",
        "interests": "Love Study Talking Web Engineering",
        "exp_qual": "Loyalty Foodie Honesty ",
        "relation_type": "longTerm",
        "social_habits": "Friends talking ",
        "past_relations": "Yes",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.01308281080747098/WhatsApp Image 2024-08-24 at 17.31.37_9b4643e0.jpg",
        "score": 33,
        "uuid": "22f45070-9192-42b0-850a-00af6e4c75b9",
        "created_at": "2024-08-24T12:05:41.172327"
    },
    {
        "id": 48,
        "user_name": "pranayy",
        "first_name": "Pranay",
        "last_name": "Buradkar",
        "email": "pnb270405@gmail.com",
        "password": "$2b$12$xqIT25iD5vGYIedoYo9yduguRGo7bl9A1cW6qIx5Zhr1LS4XFMAJe",
        "age": 19,
        "gender": "Male",
        "location": "Lucknow",
        "openness": "ambivert",
        "interests": "guitar",
        "exp_qual": "Ladki mangta",
        "relation_type": "longTerm",
        "social_habits": "playfulness ",
        "past_relations": "No",
        "values": "empathatic",
        "style": "direct",
        "traits": "lonely",
        "commitment": "long term",
        "resolution": "quick",
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.17544110536006685/WhatsApp Image 2024-08-26 at 14.43.16_f60995de.jpg",
        "score": 25,
        "uuid": "488e724b-ee0b-42e4-bfdf-a62685b788ac",
        "created_at": "2024-08-26T09:15:59.232617"
    },
    {
        "id": 51,
        "user_name": "hrushik1415",
        "first_name": "Hrushikesh",
        "last_name": "Gore",
        "email": "hrushigore15@gmail.com",
        "password": "$2b$12$wzaAxtLnWPDmuikaVMDOce8fDiw0wFSGkKnaY75HKj7dd.cp6BIwK",
        "age": 19,
        "gender": "Male",
        "location": "Lucknow",
        "openness": "introvert",
        "interests": "chess",
        "exp_qual": "intelligent",
        "relation_type": "casual",
        "social_habits": "talking",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.810691561347251/IMG_20240714_135001.jpg",
        "score": 25,
        "uuid": "00215208-c6c4-40c2-906f-780e0f84b920",
        "created_at": "2024-08-26T09:41:15.564562"
    }, {
        "id": 47,
        "user_name": "sid7singh",
        "first_name": "Sidharth",
        "last_name": "Singh",
        "email": "sidharthsingh714@gmail.com",
        "password": "$2b$12$PFx7tsSO1BrYrvsBodZJD.Avc/TRpOG9ydOFlL.Iz1rwH6J0vQ6rK",
        "age": 20,
        "gender": "Male",
        "location": "Lucknow",
        "openness": "extrovert",
        "interests": "Gaming Anime",
        "exp_qual": "Chill Person Needed",
        "relation_type": "longTerm",
        "social_habits": "sleeping",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.4795017525746883/-52xxzz.jpg",
        "score": 33,
        "uuid": "b8b03c03-e6c9-4e92-8b3c-198109209672",
        "created_at": "2024-08-26T09:15:06.894908"
    },  {
        "id": 43,
        "user_name": "lakshya5",
        "first_name": "Lakshya",
        "last_name": "Agarwal",
        "email": "agarwallakshya94@gmail.com",
        "password": "$2b$12$ZTC0.fVLPq7XZcvhvn0mg.YmjlTFQXb4H0WL0PeBMsBYbL4cgaXZC",
        "age": 23,
        "gender": "Male",
        "location": "lucknow",
        "openness": "introvert",
        "interests": "sports drama literature",
        "exp_qual": "loyalty",
        "relation_type": "longTerm",
        "social_habits": "travelling",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.5677994646277913/mypic.jpg",
        "score": 55,
        "uuid": "3a71725e-63f1-4e2f-9096-b512f5344e45",
        "created_at": "2024-08-26T08:55:33.835137"
    },
    {
        "id": 52,
        "user_name": "sharan",
        "first_name": "sharan",
        "last_name": "garikapati",
        "email": "saigarikapati1@gmail.com",
        "password": "$2b$12$5BbcLxaiKA26m4EijBK.tuBYYSm8iTUxxa/YqKZlobvVkDBfAtx9q",
        "age": 19,
        "gender": "Male",
        "location": "lucknow",
        "openness": "introvert",
        "interests": "music,anime",
        "exp_qual": "communication ,sense of humor ,support",
        "relation_type": "longTerm",
        "social_habits": "social communication",
        "past_relations": "No",
        "values": null,
        "style": null,
        "traits": null,
        "commitment": null,
        "resolution": null,
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.7695704083146808/sharan photo.jpg",
        "score": 47,
        "uuid": "e122a1b0-b9a6-4499-99fa-3a688a62c20d",
        "created_at": "2024-08-26T09:52:24.487364"
    }

]


export const sampleData2 = [{
    "id": 32,
    "user_name": "maneesh",
    "first_name": "Maneesh",
    "last_name": "Shukla",
    "email": "lit2023040@iiitl.ac.in",
    "password": "$2b$12$20.Bz9.//ekKTLaSTgJ2guzRKt7tT7Sm8H3OOcUOOxUuDIVxX.PXK",
    "age": 20,
    "gender": "Male",
    "location": "Pratapgarh",
    "openness": "extrovert",
    "interests": "Lund",
    "exp_qual": "beautiful honest respect loyal",
    "relation_type": "shortTerm",
    "social_habits": "Nightout ",
    "past_relations": "no",
    "values": null,
    "style": null,
    "traits": null,
    "commitment": null,
    "resolution": null,
    "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.1478504532002327/WhatsApp Image 2024-08-24 at 17.25.20_71a8bb0f.jpg",
    "score": 50,
    "uuid": "20245b74-b245-45c7-90b5-d5322a11b433",
    "created_at": "2024-08-24T11:55:59.676097"
},
 {
"id": 38,
"user_name": "anujgarg",
"first_name": "Karan",
"last_name": "Agarwal",
"email": "lit2023011@iiitl.ac.in",
"password": "$2b$12$CIUnG2.Ya7RkJJWLjLJEP.0REyokdzjxxc84cOCZbVhCc6SmKNU5e",
"age": 20,
"gender": "Male",
"location": "Agra",
"openness": "extrovert",
"interests": "Sports",
"exp_qual": "Love",
"relation_type": "casual",
"social_habits": "Talking",
"past_relations": "Yes",
"values": null,
"style": null,
"traits": null,
"commitment": null,
"resolution": null,
"image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.5071031884144366/WhatsApp Image 2024-08-26 at 14.06.37_fa4db545.jpg",
"score": 40,
"uuid": "45ff40b0-2234-454d-8dbe-41f8b3ac5b16",
"created_at": "2024-08-26T08:37:54.139906"
}

]


export const sampleData3 = [{        "id": 50,
    "user_name": "Pranay26",
    "first_name": "Pranay",
    "last_name": "Deshpande",
    "email": "pranayd2005@gmail.com",
    "password": "$2b$12$6WnIl/mVUEmp203VkFMvUOb9QYvpkIgTE.Gozz5qcrcMLOEJpBIQS",
    "age": 20,
    "gender": "Male",
    "location": "Lucknow",
    "openness": "ambivert",
    "interests": "Cricket,football,guitar",
    "exp_qual": "Tall and skilled in backed react",
    "relation_type": "casual",
    "social_habits": "",
    "past_relations": "Yes",
    "values": null,
    "style": null,
    "traits": null,
    "commitment": null,
    "resolution": null,
    "image_url": "",
    "score": 25,
    "uuid": "a142ab6e-41ae-42e5-a055-dfec9c04c8c7",
    "created_at": "2024-08-26T09:39:06.057856"
},  {
    "id": 49,
    "user_name": "ShreyashDhoot",
    "first_name": "Shreyash",
    "last_name": "Dhoot",
    "email": "shreyashdhoot@gmail.com",
    "password": "$2b$12$2ePJW5tbhqogJvWu0OoMuueNtkIh9u3Nq8pSUMsbcZU8Bk092FxVW",
    "age": 19,
    "gender": "Male",
    "location": "Pune,Maharashtra",
    "openness": "ambivert",
    "interests": "cooking,hiking,running,cinefile",
    "exp_qual": "funny,outgoing,intresting,foodie",
    "relation_type": "longTerm",
    "social_habits": ".",
    "past_relations": "Yes",
    "values": null,
    "style": null,
    "traits": null,
    "commitment": null,
    "resolution": null,
    "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.4428193964712901/IMG20240107175148.jpg",
    "score": 33,
    "uuid": "778e536c-c1b7-421b-89cf-4cb59deac491",
    "created_at": "2024-08-26T09:37:31.091455"
},
]


export const sampleData4 = [
    {
        "boy_email_id" : "Rishi",
        "contest_score":"45",
    },
    {
        "boy_email_id" : "Ashutosh",
        "contest_score":"40",
    }


]

export const sampleData5 = [
    {
        "boy_email_id" : "lit2023040@iiitl.ac.in",
        "girl_email_id" : "natasha@iiitl.ac.in",
        "image_url": "https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.1478504532002327/WhatsApp Image 2024-08-24 at 17.25.20_71a8bb0f.jpg",
        "flag":"0",
        "contest_score":"0",
        "first_name": "Maneesh",
        "last_name": "Shukla",
        "age": 20,
        "gender": "Male",
        "location": "Pratapgarh",
        "openness": "extrovert", 
    },{
        "boy_email_id" : "lit2023011@iiitl.ac.in",
        "girl_email_id" : "anujgarg@iiitl.ac.in",
        "image_url":"https://soundscorebucket.s3.ap-south-1.amazonaws.com/beats/undefined/0.5071031884144366/WhatsApp Image 2024-08-26 at 14.06.37_fa4db545.jpg",
        "flag":"1",
        "contest_score":"50",
        "first_name": "Karan",
        "last_name": "Agarwal",
        "age": 20,
        "gender": "Male",
        "location": "Agra",
      
    }
]